apiVersion: infinispan.org/v1
kind: Infinispan 
metadata:
  name: datagrid-service 
  namespace: datagrid-demo
spec:
  #Indicates two node DG cluster
  replicas: 2
  #Exposing it as external load Balancer
  expose:
    type: LoadBalancer
  #Enable security related configuration
  security:
    #Enables Authorization
    authorization:
      enabled: true    
    #Provides the mapping between the users and defined roles
    endpointSecretName: connect-secret
  # Specify the service type
  service:
    replicationFactor: 2
    type: DataGrid
  # Specify the details for the configuration listener
  configListener:
    logging:
      level: info
    enabled: true
    cpu: 1000m
    memory: 1024Mi